version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: qarbour_php
    volumes:
      - ./src:/var/www
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: qarbour_nginx
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - app-network

  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - app-network

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - app
      - selenium-hub
      - chrome
    command: pytest tests/
    networks:
      - app-network
    volumes:
      - ./tests:/app/tests

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
