FROM python

WORKDIR /app

# Create a virtual environment
RUN python -m venv venv
ENV PATH="/app/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# By default, run all tests using pytest
CMD ["pytest", "tests"]
